<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="jest tests" tests="6" failures="3" errors="0" time="5.184">
  <testsuite name="stack operation test" errors="0" failures="3" skipped="0" timestamp="2024-03-01T08:53:23" time="5.122" tests="6">
    <testcase classname="stack operation test Clicking on the push button should push the item to the bottom of the stack board" name="stack operation test Clicking on the push button should push the item to the bottom of the stack board" time="1.44">
    </testcase>
    <testcase classname="stack operation test Without any input clicking on push button should show output “Please input a value”" name="stack operation test Without any input clicking on push button should show output “Please input a value”" time="0.296">
    </testcase>
    <testcase classname="stack operation test Peek button click should show an output “operation not allowed” if the stack board is empty." name="stack operation test Peek button click should show an output “operation not allowed” if the stack board is empty." time="0.331">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledWith(...expected)

Expected: &quot;Operation not allowed!&quot;
Received: &quot;Operation not allowed&quot;

Number of calls: 1
    at Object.toHaveBeenCalledWith (/projects/challenge/test/test.js:61:30)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:121:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="stack operation test Clicking on the “empty” button should show output whether the stack is empty or not." name="stack operation test Clicking on the “empty” button should show output whether the stack is empty or not." time="0.292">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledWith(...expected)

Expected: &quot;Yes, Stack is empty&quot;
Received: &quot;Yes, Stack is empty!&quot;

Number of calls: 1
    at Object.toHaveBeenCalledWith (/projects/challenge/test/test.js:68:30)
    at Promise.then.completed (/projects/challenge/node_modules/jest-circus/build/utils.js:298:28)
    at new Promise (&lt;anonymous&gt;)
    at callAsyncCircusFn (/projects/challenge/node_modules/jest-circus/build/utils.js:231:10)
    at _callCircusTest (/projects/challenge/node_modules/jest-circus/build/run.js:316:40)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at _runTest (/projects/challenge/node_modules/jest-circus/build/run.js:252:3)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:126:9)
    at _runTestsForDescribeBlock (/projects/challenge/node_modules/jest-circus/build/run.js:121:9)
    at run (/projects/challenge/node_modules/jest-circus/build/run.js:71:3)
    at runAndTransformResultsToJestFormat (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:122:21)
    at jestAdapter (/projects/challenge/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
    at runTestInternal (/projects/challenge/node_modules/jest-runner/build/runTest.js:367:16)
    at runTest (/projects/challenge/node_modules/jest-runner/build/runTest.js:444:34)</failure>
    </testcase>
    <testcase classname="stack operation test Clicking on the peek button should return the item on the top of the stack, without removing it." name="stack operation test Clicking on the peek button should return the item on the top of the stack, without removing it." time="0.28">
      <failure>Error: expect(jest.fn()).toHaveBeenCalledWith(...expected)

Expected: &quot;Top Value is: item2&quot;
Received: &quot;Top item:item2&quot;

Number of calls: 1
    at Object.toHaveBeenCalledWith (/projects/challenge/test/test.js:94:30)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)</failure>
    </testcase>
    <testcase classname="stack operation test While pushing an item if stack board is full should show the output “Stack was already full!” and there is no change in the existing stack." name="stack operation test While pushing an item if stack board is full should show the output “Stack was already full!” and there is no change in the existing stack." time="0.253">
    </testcase>
  </testsuite>
</testsuites>